"""reports subscribers covered_events

Revision ID: 1acd36659b4a
Revises: a2cdaadcb567
Create Date: 2026-08-11 09:18:07.797111

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1acd36659b4a'
down_revision: Union[str, None] = 'a2cdaadcb567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covered_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_title', sa.String(length=300), nullable=False),
    sa.Column('first_covered_week', sa.Date(), nullable=False),
    sa.Column('last_updated_week', sa.Date(), nullable=False),
    sa.Column('source_urls', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_covered_events_last_updated_week'), 'covered_events', ['last_updated_week'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.String(length=4000), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_slug'), 'reports', ['slug'], unique=True)
    op.create_index(op.f('ix_reports_week_of'), 'reports', ['week_of'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    op.create_table('report_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body_markdown', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_sections_report_id'), 'report_sections', ['report_id'], unique=False)
    op.create_table('report_highlights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['companies.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'ticker', name='uq_report_highlights_report_ticker')
    )
    op.create_index(op.f('ix_report_highlights_report_id'), 'report_highlights', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_highlights_report_id'), table_name='report_highlights')
    op.drop_table('report_highlights')
    op.drop_index(op.f('ix_report_sections_report_id'), table_name='report_sections')
    op.drop_table('report_sections')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_reports_week_of'), table_name='reports')
    op.drop_index(op.f('ix_reports_slug'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_covered_events_last_updated_week'), table_name='covered_events')
    op.drop_table('covered_events')
    # ### end Alembic commands ###
