"""initial schema

Revision ID: a2cdaadcb567
Revises: 
Create Date: 2026-08-10 10:49:54.507482

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2cdaadcb567'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=1), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('weight_profile', sa.JSON(), nullable=False),
    sa.Column('methodology_version', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('company_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_score_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.ForeignKeyConstraint(['current_score_id'], ['score_history.id'], name='fk_companies_current_score', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cohort_id'), 'companies', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('financial_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=4), nullable=False),
    sa.Column('raw_fields', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_date', 'period', name='uq_financial_facts_company_period')
    )
    op.create_index(op.f('ix_financial_facts_company_id'), 'financial_facts', ['company_id'], unique=False)
    op.create_table('score_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('composite_band', sa.String(length=20), nullable=False),
    sa.Column('sector_percentile', sa.Float(), nullable=False),
    sa.Column('sector_percentile_band', sa.String(length=30), nullable=False),
    sa.Column('coverage_pct', sa.Float(), nullable=False),
    sa.Column('low_reliability', sa.Boolean(), nullable=False),
    sa.Column('regime', sa.String(length=30), nullable=False),
    sa.Column('cohort_size', sa.Integer(), nullable=False),
    sa.Column('extended_cohort', sa.Boolean(), nullable=False),
    sa.Column('distress_ceiling_applied', sa.Boolean(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'week_of', name='uq_score_history_company_week')
    )
    op.create_index(op.f('ix_score_history_company_id'), 'score_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_score_history_composite_score'), 'score_history', ['composite_score'], unique=False)
    op.create_index(op.f('ix_score_history_week_of'), 'score_history', ['week_of'], unique=False)
    op.create_table('category_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score_history_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['score_history_id'], ['score_history.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_history_id', 'category_name', name='uq_category_scores_history_name')
    )
    op.create_index(op.f('ix_category_scores_score_history_id'), 'category_scores', ['score_history_id'], unique=False)
    op.create_table('risk_metrics',
    sa.Column('score_history_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=30), nullable=False),
    sa.Column('altman_z', sa.Float(), nullable=True),
    sa.Column('altman_zone', sa.String(length=20), nullable=False),
    sa.Column('piotroski_f', sa.Integer(), nullable=True),
    sa.Column('net_debt_ebitda', sa.Float(), nullable=True),
    sa.Column('interest_coverage', sa.Float(), nullable=True),
    sa.Column('cash_runway_months', sa.Float(), nullable=True),
    sa.Column('burn_multiple', sa.Float(), nullable=True),
    sa.Column('dilution_yoy_pct', sa.Float(), nullable=True),
    sa.Column('components_used', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['score_history_id'], ['score_history.id'], ),
    sa.PrimaryKeyConstraint('score_history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_metrics')
    op.drop_index(op.f('ix_category_scores_score_history_id'), table_name='category_scores')
    op.drop_table('category_scores')
    op.drop_index(op.f('ix_score_history_week_of'), table_name='score_history')
    op.drop_index(op.f('ix_score_history_composite_score'), table_name='score_history')
    op.drop_index(op.f('ix_score_history_company_id'), table_name='score_history')
    op.drop_table('score_history')
    op.drop_index(op.f('ix_financial_facts_company_id'), table_name='financial_facts')
    op.drop_table('financial_facts')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_cohort_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('ingestion_runs')
    op.drop_table('cohorts')
    # ### end Alembic commands ###
